services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '192.168.1.141'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.141:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '2424:22'
    shm_size: '256m'